### ISSUE TITLE
Error: The process was terminated due to an unhandled exception.

### ISSUE THREAD

**Issue by rafalfitt** [thalpius/Microsoft-Defender-for-Identity-Configuration-Checker#4]
Application: Microsoft.Defender.for.Identity.Configuration.Checker.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.DirectoryServices.DirectoryServicesCOMException
   at System.DirectoryServices.DirectoryEntry.Bind(Boolean)
   at System.DirectoryServices.DirectoryEntry.Bind()
   at System.DirectoryServices.DirectoryEntry.get_AdsObject()
   at System.DirectoryServices.DirectoryEntry.get_Options()
   at Microsoft_Defender_for_Identity_Configuration_Checker.ExchangeAuditing.CheckExchangeAuditing()
   at Microsoft_Defender_for_Identity_Configuration_Checker.FormDashboard.RefreshExchangeAuditing()
   at Microsoft_Defender_for_Identity_Configuration_Checker.FormDashboard..ctor()
   at Microsoft_Defender_for_Identity_Configuration_Checker.Program.Main()

Faulting application name: Microsoft.Defender.for.Identity.Configuration.Checker.exe, version: 1.0.0.3, time stamp: 0xf74815f2
Faulting module name: KERNELBASE.dll, version: 10.0.17763.3532, time stamp: 0xc92babb8
Exception code: 0xe0434352
Fault offset: 0x0000000000034859
Faulting process id: 0x1f1c
Faulting application start time: 0x01d925e6c7072805
Faulting application path: C:\Users\Administrator\Desktop\Microsoft.Defender.for.Identity.Configuration.Checker.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: 7c25952d-7524-4f06-9ece-544f7536cccf
Faulting package full name: 
Faulting package-relative application ID:

**Comment by thalpius** [comment]
@rafalfitt do you remember when you got this error?

**Comment by rafalfitt** [comment]
@thalpius sure, 15h ago I tried to run it directly on one of DCs.
When the app is started without administrator privileges (without "Run as administrator"), it starts without any problem.

DC is configured with full UAC even for the Administrator user.

**Comment by rafalfitt** [comment]
sorry, but your explanation is not valid for my scenario.

**Comment by thalpius** [comment]
Try the compiler binary I added at the releases.
